version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${API_PORT:-8080}:8080
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:14
    command: -c 'max_connections=500'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:5432

  migrate:
    image: rust:1.78
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "
        cargo install diesel_cli --no-default-features --features postgres &&
        diesel setup &&
        diesel migration run
      "

volumes:
  postgres_data:
