version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: ['/usr/local/bin/wait-for-db.sh', 'cargo', 'run', '--release']
    environment:
      - DATABASE_URL=postgres://forestry:optimizer@db/forestryoptimizer
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: forestry
      POSTGRES_PASSWORD: optimizer
      POSTGRES_DB: forestryoptimizer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
